### PR TITLE
Add support for Yarn Cluster

### LINKED ISSUE #181: Support for yarn-cluster mode
Currently, sparklyr submits a custom `sparklyr.jar` file through spark-submit with a given ports file. Then the jar initializes a socket and saves the socket details in the ports file. This file is used by sparklyr to rea this socket definition and connect to the running application within the jar in the driver machine. This works as expected for `yarn-client`; however, for `yarn-cluster` the file is located on a different machine that the r process running `sparklyr` won't be able to locate since it's not local anymore.

Marking this as feature request for discussion and planning work for next release.

### PR DESCRIPTION
**Pull request by javierluraschi**
@statmatt willing to try this PR attempting to add `YARN-CLUSTER` support?

**Background:**
- *Yarn-Client* runs the `sparklyr` backend on the same machine. In the past, just like `sparkR`, `sparklyr` used a file to communicate the port number back to the client. This restriction was removed with the [Gateway PR](https://github.com/rstudio/sparklyr/pull/238).
- *Yarn-Cluster* runs the `sparklyr` backend potentially on a different machine, the remote driver. While this would be challenging to accomplish with the ports file, using the `sparklyr.gateway.address` config option should be enough to workaround this.

**Implementation:**
In order to support `YARN-CLIENT`, it is my understanding that all we need to do is get this information from `yarn-site.xml` which should be set under `YARN_CONF_DIR`, that's about it.

**Example:**
This PR needs additional testing but worth trying out as follows:

```r
devtools::install_github("rstudio/sparklyr", ref = "feature/yarn-cluster")
```

```r
sc <- spark_connect(master = "yarn-cluster")
```

or explicitly as:

```r
sc <- spark_connect(
  master = "yarn-cluster",
  config = list(sparklyr.gateway.address = "<driver-node>")
)
```

### CODE REVIEW

**Comment by statmatt** [comment]
yup. will contact directly for instructions.

**Comment by statmatt** [comment]
`> sc <- spark_connect(master="yarn-cluster", app_name="test - yarn cluster", spark_home = "/usr/local/Cellar/apache-spark/2.1.0", config = list(sparklyr.gateway.address = "172.31.244.222"))
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (8517): Gateway in port (8880) did not respond.
    Path: /usr/local/Cellar/apache-spark/2.1.0/bin/spark-submit
    Parameters: --class, sparklyr.Shell, '/Users/Matt/Library/R/3.2/library/sparklyr/java/sparklyr-2.1-2.11.jar', 8880, 8517
    Log: /var/folders/kt/9nltjw6j26z37yg9g0k4s6sw0000gn/T//RtmpwcnYu0/file9e5f356f0f9_spark.log


---- Output Log ----
17/07/19 14:43:15 INFO sparklyr: Session (8517) is starting under 127.0.0.1 port 8880
17/07/19 14:43:15 INFO sparklyr: Session (8517) found port 8880 is not available
17/07/19 14:43:15 INFO sparklyr: Backend (8517) is registering session in gateway
17/07/19 14:43:15 INFO sparklyr: Backend (8517) is waiting for registration in gateway
17/07/19 14:43:15 INFO sparklyr: Backend (8517) finished registration in gateway with status 0
17/07/19 14:43:15 INFO sparklyr: Backend (8517) is waiting for sparklyr client to connect to port 58717

---- Error Log ----
>`

**Comment by javierluraschi** [comment]
@statmatt my bad, two issues now fixed, but that won't solve the error you mentioned...

1. I wrote `yarn-client.xml` in the instructions when the code uses `yarn-site.xml`, fixed the PR instructions above.
2. I noticed code was using `HADOOP_CONF_DIR` when `YARN_CONF_DIR` should have been used instead since some clusters might not use hadoop.

This PR has been updated, you will need to rerun:

```
devtools::install_github("rstudio/sparklyr", ref = "feature/yarn-cluster")
```

**Comment by javierluraschi** [comment]
@statmatt regarding this error: `17/07/19 14:43:15 INFO sparklyr: Backend (8517) is waiting for sparklyr client to connect to port 58717`, looks like port 58717 is not externally available for the R client to connect.

Would you expect port `58717` to be accessible? Looks like we might need a range of ports that `sparklyr` uses rather than arbitrary ones. Which ports would you be able to open on that driver node?

**Comment by javierluraschi** [comment]
Actually... I think we need one more change... one sec.

**Comment by javierluraschi** [comment]
@statmatt some fixes went in, try `sparkly 0.5.6-9020` instead by running `devtools::install_github("rstudio/sparklyr", ref = "feature/yarn-cluster")`.

Now we try to read `YARN_CONF_DIR` but fall back to `HADOOP_CONF_DIR` to find `yarn-site.xml`

**Comment by statmatt** [comment]
> sc <- spark_connect(master="yarn-cluster", app_name="test - yarn cluster", spark_home = "/usr/local/Cellar/apache-spark/2.1.0", config = list(sparklyr.gateway.address = "172.31.244.222"))
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (5206): Gateway in port (8880) did not respond.
    Path: /usr/local/Cellar/apache-spark/2.1.0/bin/spark-submit
    Parameters: --class, sparklyr.Shell, '/Users/Matt/Library/R/3.2/library/sparklyr/java/sparklyr-2.1-2.11.jar', 8880, 5206
    Log: /var/folders/kt/9nltjw6j26z37yg9g0k4s6sw0000gn/T//RtmpwcnYu0/file9e5f631e8e9a_spark.log


---- Output Log ----
17/07/19 17:02:54 INFO sparklyr: Session (5206) is starting under 127.0.0.1 port 8880
17/07/19 17:02:54 INFO sparklyr: Session (5206) found port 8880 is not available
17/07/19 17:02:54 INFO sparklyr: Backend (5206) is registering session in gateway
17/07/19 17:02:54 INFO sparklyr: Backend (5206) is waiting for registration in gateway
17/07/19 17:02:54 INFO sparklyr: Backend (5206) finished registration in gateway with status 0
17/07/19 17:02:54 INFO sparklyr: Backend (5206) is waiting for sparklyr client to connect to port 62355

---- Error Log ----

**Comment by javierluraschi** [comment]
@statmatt pushed another fix, the problem is that in your logs `Session (5206) found port 8880 is not available` means that someone else already started the `sparklyr` gateway, which means that it's not enabled to take remote connections. Changed `sparklyr` to, by default, accept remote connections.

You will have to make sure that all sparklyr applications are killed in the cluster, then run:

```
devtools::install_github("rstudio/sparklyr", ref = "feature/yarn-cluster")
```

We expect to see in the logs:

```
is configuring for remote connections
```

which would mean that `sparklyr` is ready to take remote clients connections.

**Comment by javierluraschi** [comment]
Followed up offline with @statmatt, here are my findings:

### Using Yarn-Cluster within EMR

I was able to validate we can use `yarn-cluster` in sparklyr from within EMR machines. Worked with @statmatt to iron out some of the connection issues and finishes a couple more within a different cluster. See screenshot below.

screen shot 2017-07-20 at 3 42 31 pm

### Using Yarn-Cluster outside EMR

@statmatt also attempted to connect to `yarn-cluster` from within an external machine to EMR. While this should be possible, see [Remotely submit jobs to YARN](http://theckang.com/2015/remote-spark-jobs-on-yarn/) and the image below, it proved to be more complex than expected. The problem is that `spark-submit` assumes that the current machine is a member of HDFS since it uses this functionality to copy the jars into the cluster, I also experienced errors from the `Timeline Service` that were fixable with `yarn.timeline-service.enabled=FALSE` in `yarn-site.xml`. That said, there is a significant amount of configuration required. The recommendation would be to use `master="yarn-cluster"` only from within cluster machines already correctly configured.

### Using Gateway outside EMR

For connections from within a VPN (say Amazons VPC), another possible approach this PR enables is using the gateway connection. For instance, this enables running from EMR:

```
/usr/lib/spark/bin/spark-submit --class sparklyr.Shell --master yarn --deploy-mode client
/home/hadoop/R/x86_64-redhat-linux-gnu-library/3.3/sparklyr/java/sparklyr-2.1-2.11.jar
8885 123123 --remote
```

And then remote connecting to this cluster using:

```r
sc <- spark_connect(
   master = "sparklyr://ec2-54-71-124-108.us-west-2.compute.amazonaws.com:8885/123123"
)
```

**NOTE:** This approach is only secured by a session-id (123123 in the example above) and therefore, it is strongly recommended to only use this from within a VPN. Outside VPNs, Livy with Authentication should be preffered.

**Pull request merged**
