### PR TITLE
Support configuring library path in spark_apply()

### PR DESCRIPTION
**Pull request by javierluraschi**
See https://github.com/rstudio/sparklyr/issues/1530

### CODE REVIEW

**Comment by mattpollock** [comment]
Just tested this in a YARN environment and it worked great. My only suggestion is that the default value of `packages=` depend on whether `spark.r.libpaths` is set. If it is not, then the current `packages=TRUE` default seems good. If it is however then much of the point of specifying the configuration is to avoid the copy operation. If `packages=TRUE` then there are likely to be frustrated users who forget to set `packages=FALSE` for every call to `spark_apply`

**Comment by mattpollock** [comment]
I would actually prefer `packages=FALSE` as a general default (make users think about it before their entire `.libPaths()` dirs are copied up to each executor), but recognize that this would be a breaking change for some users.

**Comment by javierluraschi** [comment]
@mattpollock good to hear, and yes, good suggestion. I'll implement this with a new configuration parameter `sparklyr.apply.packages` which you can see to `FALSE` but others could set to a subset of packages too copy, etc.

**Comment by mattpollock** [comment]
Looks good to me. Thanks for a quick response on this feature add! I'm happy to kill my clunky work around capturing of `f` and wrapping it in a function that calls `.libPaths`.

**Pull request merged**
