### PR TITLE
get model coefficients, not the function

### PR DESCRIPTION
**Pull request by shabbybanks**
This should fix part of #1596 : fitting a model without an intercept term. The main problem of #1596 is still open, however.

### CODE REVIEW

**Comment by javierluraschi** [comment]
@kevinykuo this one looks like a safe merge since `coefficients` is not defined, but worth double checking in case I missed something.

**Comment by javierluraschi** [comment]
Thank you, @shabbybanks.

**Comment by kevinykuo** [comment]
@shabbybanks Thanks! Could you also contribute a test for this change?

**Comment by shabbybanks** [comment]
ah, ok. I will. Since the code previously threw an error, when now it should not, do you have a preferred `testthat` idiom for testing 'does not throw an error'? Would it be `expect_error(f(), NA)`?

**Pull request merged**
