### PR TITLE
Allow for splitting / extraction of elements from vector-columns (list-columns)

### PR DESCRIPTION
**Pull request by kevinushey**
This PR introduces a couple of helper functions for extracting elements from vector-columns -- typically, those returned by e.g. `sdf_predict()` or otherwise. See the test file for example usages.

I'm not entirely happy with the function names -- we should think about whether we could get something a bit more descriptive.

### CODE REVIEW

**Comment by javierluraschi** [comment]
LGTM. I don't have better suggestions for naming `sdf_extract_column` and `sdf_split_column`, both seem reasonable to me.

**Comment by kevinykuo** [comment]
We'll have both `sdf_separate_column()` and `separate.tbl_spark` (from tidyr)?

**Comment by kevinushey** [comment]
Right -- for now, we'll just have a separate `sdf_separate_column()` analog but we'll also provide a method for `tidyr` if possible. The interface for `tidyr::separate()` is a bit more complicated so I wanted to get a simple standalone version in first if possible.

**Comment by kevinushey** [comment]
Note to self: before merging, we should make sure this works with e.g. the return value of tokenizers.

**Pull request closed without merging**
