### PR TITLE
Add support for group_by under spark_apply

### PR DESCRIPTION
**Pull request by javierluraschi**
Users have requested the ability to perform arbitrary linear regressions (and other modeling techniques) at scale while grouping data over a given key. See https://github.com/rstudio/sparklyr/issues/770. This PR enables such scenario, for instance:

```r
library(sparklyr)
sc <- spark_connect(master = "local")
iris_tbl <- sdf_copy_to(sc, iris)

spark_apply(
  iris_tbl,
  function(e) lm(Petal_Width ~ Petal_Length, e)$coefficients[["(Intercept)"]],
  names = "Intercept",
  group_by = "Species"
)
```

```
# Source:   table<sparklyr_tmp_155e81fd2c9cc> [?? x 1]
# Database: spark_connection
    Intercept
        <dbl>
1 -0.08428835
2  1.13603130
3 -0.04822033
```

### CODE REVIEW

**Comment by statmatt** [comment]
This is awesome. Thank you!

**Comment by kevinykuo** [comment]
How would users attach the grouping column(s) to the resulting DataFrame with this API?

**Comment by statmatt** [comment]
a good point kevin ... in the SparkR version, you have the option of attaching it as the function takes two arguments (the key and the dataframe that represents the data for the key). then it's up to the user to decide how to attach the key.

might not be easy to do here given how this was specified (or maybe it is) to have the function have to take two arguments if group_by is specified?

**Comment by javierluraschi** [comment]
Right now we give you back everything, including the grouped column. So for instance, to get a `Species` column with the grouped key you would run:

```r
spark_apply(
  iris_tbl,
  function(d) data.frame(d$Species[[1]], lm(Petal_Width ~ Petal_Length, d)$coefficients[["(Intercept)"]]),
  names = c("Species", "Intercept"),
  group_by = "Species"
)
```

```
# Source:   table<sparklyr_tmp_36216a2aa338> [?? x 2]
# Database: spark_connection
     Species   Intercept
       <chr>       <dbl>
1 versicolor -0.08428835
2  virginica  1.13603130
3     setosa -0.04822033
```

However, for ease of use, adding the key as follows:

```r
spark_apply(
  iris_tbl,
  function(d, g) data.frame(g, lm(Petal_Width ~ Petal_Length, d)$coefficients[["(Intercept)"]]),
  names = c("Species", "Intercept"),
  group_by = "Species"
)
```

```
# Source:   table<sparklyr_tmp_36216a2aa338> [?? x 2]
# Database: spark_connection
     Species   Intercept
       <chr>       <dbl>
1 versicolor -0.08428835
2  virginica  1.13603130
3     setosa -0.04822033
```

**Pull request merged**
