### PR TITLE
WIP: fix dbi 0.5.13 breaking change from #351

### PR DESCRIPTION
**Pull request by javierluraschi**
Breaking change coming in DBI, see: https://github.com/rstudio/sparklyr/issues/351

CC: @jjallaire @kevinushey Is there a more generic way to handle this than to embrace the new signature and bump the required version?

### CODE REVIEW

**Comment by jjallaire** [comment]
Is the updated version of DBI on CRAN? If so then I think this is indeed the right change.

**Comment by javierluraschi** [comment]
@jjallaire the DBI change is not yet in CRAN. I'm coordinating when this will happen with @krlmlr to push push a fix on time.

**Comment by jjallaire** [comment]
Okay, sounds good!

**Comment by krlmlr** [comment]
I wonder why you need to specialize if you're only forwarding to the DBI implementation.

**Comment by javierluraschi** [comment]
@krlmlr We do need to specialize, I think, since we morph the `spark_connection` object as a `DBI` connection object, so when you connect to Spark using `sparklyr`, you get a connection that can be used with different packages (dplyr, sparklyr, DBI, etc.).

I just pushed one more iteration to this branch, since we don't use the specialized versions, I'm using the right `setMethod` based on the DBI version. Works for both versions of DBI; however, it does seem a bit hacky. Is this fix a strech? @jjallaire

**Comment by kevinushey** [comment]
@javierluraschi I'm not sure if your most recent change will work as intended. This is code that will be run at package build time; therefore, it will depend on what version of `DBI` is available when `sparklyr` is built.

If a user downloads a `sparklyr` binary from CRAN, but has an older version of `DBI` installed locally, this might break. If you _really_ want to try being clever here, you could move the associated code into the `.onLoad()` function, but I'm not sure if mucking around with S4 method registration at package load time will work as expected, either.

All in all I would vote for not trying to do anything too clever and just synchronize the release with `DBI` (avoid a package version check altogether here).

**Comment by javierluraschi** [comment]
@kevinushey thanks for taking a look here! Some questions... when a package gets built, it replaces the code with an `rdb` file. Not sure how to decompile this binary representation, but I'm curious as to what happens to the `setMethod` directives once "compiled". Does the `rdb` file actually contains a binary format or is it rather still text sources compressed? There is no VM for R so the "compilation" step must be pretty basic, isn't it? Also, how can we validate that this last fix breaks something? I tried compiling from the the IDE the package and then testing against both DBI versions,  but I wasn't to spot any problems while using `soparklyr` with `DBI` operations.

That said, since are skeptic of the last fix, this is good enough reason to revert to the less generic one. However, it would be nice to come up with a different workaround that supports both versions. Otherwise, older versions of sparklyr will be broken with newer versions of DBI and we will have to coordinate another release of sparklyr with the DBI release for this change which would be good to avoid if possible.

I'll leave this PR open since there is no rush of merging this until `DBI` releases again to CRAN at some point.

**Comment by javierluraschi** [comment]
@krlmlr provided a different fix in `DBI` that is backwards compatible, closing this PR.

See comments in: https://github.com/rstats-db/DBI/issues/147

**Comment by krlmlr** [comment]
This still needs to be changed after CRAN release of DBI, but then you can simply use the new signature.

**Pull request closed without merging**
