### PR TITLE
Add support to write JDBC or to Generic Sources

### PR DESCRIPTION
**Pull request by javierluraschi**
See https://github.com/rstudio/sparklyr/issues/851. @JakeRuss 

This PR adds support for writing data to a JDBC (or generic source) as follows:

Read data:

```r
devtool::isntall_github("rstudip/sparklyr", ref "spark-write-jdbc")

config <- spark_config()
config$`sparklyr.shell.driver-class-path` <- 
  "~/Downloads/mysql-connector-java-5.1.41/mysql-connector-java-5.1.41-bin.jar"

sc <- spark_connect(master = "local",
                    version = "2.1.0",
                    config = config)

spark_read_jdbc(sc, "person_jdbc",  options = list(
  url = "jdbc:mysql://localhost:3306/sparklyr",
  user = "root",
  password = "<password>",
  dbtable = "person"))
```

Write data:

```r
spark_write_jdbc(sc, "person_spark",  options = list(
  url = "jdbc:mysql://localhost:3306/sparklyr",
  user = "root",
  password = "<password>"))
```

### CODE REVIEW

**Comment by JakeRuss** [comment]
Oh, that's fantastic @javierluraschi! Really great for you to add this support so quickly. I will go and test this now and report back.

One question I have is how do I control whether `spark_write_jdbc()` overwrites an existing database table or appends to it?

**Comment by javierluraschi** [comment]
@JakeRuss using `mode`, available options: https://spark.apache.org/docs/2.1.0/api/scala/index.html#org.apache.spark.sql.DataFrameWriter, so for instance:

**Append:**

```r
spark_write_jdbc(sc, "person_spark",  options = list(
  url = "jdbc:mysql://localhost:3306/sparklyr",
  user = "root",
  password = "<password>"), mode = "append")
```

**Overwrite:**

```r
```r
spark_write_jdbc(sc, "person_spark",  options = list(
  url = "jdbc:mysql://localhost:3306/sparklyr",
  user = "root",
  password = "<password>"), mode = "overwrite")
```
```

**Comment by JakeRuss** [comment]
When in doubt, read the documentation :pensive: 

Does this function require Spark 2.1.0? Because after installing and testing it with Spark 1.6.0, I get the following error messages,
```
spark_write_jdbc(test_spark_tbl, 
                 name    = "person_spark",
                 options = list(url      = "jdbc:mysql://localhost:3306/automation",
                                user     = "root",
                                password = "<password>",
                                dbtable  = "person_spark"), mode = "append")
```
```
Error: java.lang.Exception: No matched method found for class org.apache.spark.sql.DataFrameWriter.jdbc
	at sparklyr.Invoke$.invoke(invoke.scala:99)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:97)
	at sparklyr.StreamHandler$.read(stream.scala:62)
	at sparklyr.BackendHandler.channelRead0(handler.scala:52)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by JakeRuss** [comment]
Thanks so much @javierluraschi! I tested both the `append` and `overwrite` cases and that seems to have fixed the issue.

**Comment by javierluraschi** [comment]
Thanks for trying this out @JakeRuss, much appreciated. Let us know if you hit any issues.

**Pull request merged**
