### PR TITLE
Handle database name

### PR DESCRIPTION
**Pull request by chezou**
This fix will support setting database name for `tbl_cache`, in other words, non-`default` databases.

e.g.

```r
tbl_cache(sc, "db_name1.table")
```

This PR also add `use_db()` for changing database.

fix: https://github.com/rstudio/sparklyr/issues/447

### CODE REVIEW

**Comment by chezou** [comment]
I found it doesn't solve the problem.

**Comment by chezou** [comment]
I confirmed this patch fixes only `tbl_cache()`, so I changed the title.

**Comment by javierluraschi** [comment]
@chezou Please rename to `db_use` to be consistent with `tbl_`, `sdf_`, `ml_`, `spark_`, `ft_`, etc. functions.

**Comment by chezou** [comment]
@javierluraschi Changed to `tbl_change_db` https://github.com/rstudio/sparklyr/pull/474/commits/e8840cc44e5bafd05ff30e5952babe5eb4dc2368

**Comment by javierluraschi** [comment]
@chezou thank you, the new name puts this function with the right family.

**Comment by bedantaguru** [comment]
Is this merged in CRAN version?

**Comment by chezou** [comment]
@bedantaguru No, not yet. I think It'll be released on [v0.6.0](https://github.com/rstudio/sparklyr/blob/master/NEWS.md#databases).

**Pull request merged**
