### PR TITLE
Allow missing master for Databricks connections

### PR DESCRIPTION
**Pull request by kevinykuo**
Pending testing on Databricks.

This should resolve both https://github.com/rstudio/sparklyr/issues/1461 and https://github.com/rstudio/sparklyr/issues/1373. Note that the default was never respected which is why it was removed.

### CODE REVIEW

**Comment by falaki** [comment]
I am testing this commit on Databricks.

**Comment by falaki** [comment]
@kevinykuo I am still getting error from `gateway_connection` in our notebooks.

```
Error in gateway_connection(paste("sparklyr://localhost:", gatewayPort,  : 
  Failed to connect to gateway: sparklyr://localhost:65529/65529
```

**Comment by kevinykuo** [comment]
@javierluraschi @falaki going to merge this, shouldn't cause any issues, but give me a shout if it does.

**Comment by falaki** [comment]
+1. And https://github.com/rstudio/sparklyr/pull/1465 should fix the backend issue.

**Pull request merged**
