### PR TITLE
Support ML for Livy

### PR DESCRIPTION
**Pull request by kevinykuo**
https://github.com/rstudio/sparklyr/issues/1300

### CODE REVIEW

**Comment by kevinykuo** [comment]
Confirmed working in emr 5.10.

**Comment by RyanChang0307** [comment]
Hi, I can't wait to use ML through Livy. I download the latest version code from GitHub and compile it on my own RStudio Server.But get the error message as below:

sc <- spark_connect(master = "http://localhost:8998", method = "livy")
Error in value[[3L]](cond) : 
  Failed to initialize livy connection: Failed to load livyutils.scala: Failed to execute Livy statement with error: <console>:118: error: not found: value Serializer
Traceback:            "Serializer" -> Serializer,
                           ^
<console>:120: error: not found: value StreamHandler
           "StreamHandler" -> StreamHandler,
                              ^
<console>:121: error: not found: value JVMObjectTracker
           "JVMObjectTracker" -> JVMObjectTracker,
                                 ^
<console>:129: error: not found: value StreamHandler
           val result = StreamHandler.read(
                        ^

**Comment by kevinykuo** [comment]
What livy/spark versions are you running?

**Comment by RyanChang0307** [comment]
Spark version: 2.2.0 with Hadoop 2.6
Both Livy 0.3.0 and 0.5.0 got the same result.

**Comment by kevinykuo** [comment]
Unable to reproduce on my end... Could you try `devtools::install_github("rstudio/sparklyr")`?

**Comment by RyanChang0307** [comment]
Hi, Kevin,

Followed by your guide, it did work with livy 0.5.0 and spark 2.2.0 on local.

But I installed livy  (0.5.0) on one of remote Cloudera Hadoop spark gateway node (spark 1.6),

and  raise the spark session through the remote livy server , got the error as below:

> library("sparklyr")
> sc <- spark_connect(master = "http://172.16.244.161:8998", method = "livy")
Error in value[[3L]](cond) : 
  Failed to initialize livy connection: Failed to load livyutils.scala: Failed to execute Livy statement with error: <console>:129: error: not found: value Repartition
Traceback:            "Repartition" -> Repartition,

**Comment by kevinykuo** [comment]
Okay could you file a new issue and link to this PR. Will take a look next week.

**Pull request merged**
